// Generated by scripts/generate-third-party-notices.sh; do not edit by hand.
// KilldeerCoreTests compares these with LICENSE and THIRD-PARTY-NOTICES.txt.

public enum Licenses {
    /// Killdeer's own license: the LICENSE file at the root of the repository.
    public static let license = #"""
MIT License

Copyright (c) 2026 Cyberneura

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

"""#

    /// The notices for everything Killdeer bundles: THIRD-PARTY-NOTICES.txt.
    public static let thirdPartyNotices = #"""
THIRD-PARTY NOTICES

Killdeer bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# Swift packages (compiled into the binary)
################################################################################

None. Killdeer has no package dependencies and bundles no third-party
libraries. It links only Apple system frameworks (Foundation, AppKit, SwiftUI,
ServiceManagement, UserNotifications, IOKit and the Darwin libraries), which are
part of macOS and are not distributed with Killdeer.

"""#
}
