#!/usr/bin/env bash
# Writes THIRD-PARTY-NOTICES.txt, and Sources/KilldeerCore/Licenses.swift which
# carries it and LICENSE into both executables (`killdeer --license` and the
# menu's Third-Party Licenses window). Run it again after adding a dependency or
# changing LICENSE, and commit both files.
#
#   scripts/generate-third-party-notices.sh           # regenerate
#   scripts/generate-third-party-notices.sh --check   # exit 1 if either file is stale
#
# The release workflow runs --check in front of the build.
#
# Killdeer has no package dependencies: it links Apple frameworks only, and those
# are part of macOS rather than something the app ships. So what this writes is a
# statement that nothing third-party is bundled. That statement is only true while
# the package has no dependencies, which is why the script checks for them first
# and refuses to write it otherwise. If a dependency is ever added, extend this to
# read each pin in Package.resolved and its license text from .build/checkouts
# (which needs a macOS machine that has run `swift package resolve`).
#
# Written for the bash 3.2 that ships with macOS.
set -euo pipefail

cd "$(dirname "$0")/.."

CHECK=false
case "${1:-}" in
  "") ;;
  --check) CHECK=true ;;
  *)
    echo "Usage: scripts/generate-third-party-notices.sh [--check]" >&2
    exit 1
    ;;
esac

NOTICES="THIRD-PARTY-NOTICES.txt"
SWIFT="Sources/KilldeerCore/Licenses.swift"

WORK=$(mktemp -d "${TMPDIR:-/tmp}/killdeer-notices.XXXXXX")
trap 'rm -rf "$WORK"' EXIT

# The manifest as SwiftPM reads it is the authority: top-level dependencies are
# every package pulled in (remote or local path), and a binary target is a
# prebuilt framework. Either means something third-party is linked in. Where
# swift is not installed the manifest cannot be evaluated, so a looser text
# search stands in (and says so); the release workflow always has swift.
if command -v swift >/dev/null 2>&1; then
  if ! swift package dump-package > "$WORK/manifest.json"; then
    echo "Error: swift package dump-package failed." >&2
    exit 1
  fi
  if ! /usr/bin/env python3 - "$WORK/manifest.json" <<'PY'
import json, sys
manifest = json.load(open(sys.argv[1]))
found = [str(d) for d in manifest.get("dependencies", [])]
found += ["binary target " + t["name"] for t in manifest.get("targets", []) if t.get("type") == "binary"]
for item in found:
    print(item, file=sys.stderr)
sys.exit(1 if found else 0)
PY
  then
    echo "Error: the package has dependencies (above). This script only knows how to write" >&2
    echo "the no-dependency notice; extend it to list the pinned packages." >&2
    exit 1
  fi
else
  echo "Note: swift not found; checking Package.swift by text search instead." >&2
  if grep -nE '\.(package|binaryTarget)[[:space:]]*(\(|$)' Package.swift >&2; then
    echo "Error: Package.swift appears to declare a dependency (above). This script only knows" >&2
    echo "how to write the no-dependency notice; extend it to list the pinned packages." >&2
    exit 1
  fi
fi

# Package.resolved is not committed while there is nothing to resolve, but a
# stale one left behind would mean the check above missed something.
if [ -f Package.resolved ] && grep -q '"identity"' Package.resolved; then
  echo "Error: Package.resolved has pins. Extend this script to list them." >&2
  exit 1
fi

cat > "$WORK/notices" <<'NOTICES'
THIRD-PARTY NOTICES

Killdeer bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# Swift packages (compiled into the binary)
################################################################################

None. Killdeer has no package dependencies and bundles no third-party
libraries. It links only Apple system frameworks (Foundation, AppKit, SwiftUI,
ServiceManagement, UserNotifications, IOKit and the Darwin libraries), which are
part of macOS and are not distributed with Killdeer.
NOTICES

# Both texts go into raw string literals (#"""..."""#), in which a backslash is
# ordinary text. The two sequences a raw literal still reacts to are refused
# rather than escaped, since neither has any business in a license.
for source in LICENSE "$WORK/notices"; do
  if grep -qF '"""#' "$source" || grep -qF '\#' "$source"; then
    echo "Error: $source contains a sequence that would end or interpolate a Swift raw string." >&2
    exit 1
  fi
done

# A multi-line literal drops the line break just before its closing delimiter,
# so the empty line after each text keeps the text's own final newline.
{
  cat <<'SWIFT'
// Generated by scripts/generate-third-party-notices.sh; do not edit by hand.
// KilldeerCoreTests compares these with LICENSE and THIRD-PARTY-NOTICES.txt.

public enum Licenses {
    /// Killdeer's own license: the LICENSE file at the root of the repository.
    public static let license = #"""
SWIFT
  cat LICENSE
  printf '\n"""#\n\n'
  printf '    /// The notices for everything Killdeer bundles: THIRD-PARTY-NOTICES.txt.\n'
  printf '    public static let thirdPartyNotices = #"""\n'
  cat "$WORK/notices"
  printf '\n"""#\n}\n'
} > "$WORK/swift"

if $CHECK; then
  stale=0
  for pair in "$WORK/notices:$NOTICES" "$WORK/swift:$SWIFT"; do
    generated="${pair%%:*}"
    committed="${pair#*:}"
    if ! cmp -s "$generated" "$committed"; then
      echo "Error: $committed is out of date. Run scripts/generate-third-party-notices.sh and commit the result." >&2
      diff -u "$committed" "$generated" >&2 || true
      stale=1
    fi
  done
  exit "$stale"
fi

# Moved into place rather than written in place, so an interrupted run cannot
# leave half a file behind. The copy lands next to its target first because a
# mv across filesystems is a copy, not a rename.
cp "$WORK/notices" "$NOTICES.tmp"
mv "$NOTICES.tmp" "$NOTICES"
cp "$WORK/swift" "$SWIFT.tmp"
mv "$SWIFT.tmp" "$SWIFT"
echo "Wrote $NOTICES and $SWIFT"
